### ISSUE TITLE
Type Error when inspecting files in windows app

### ISSUE THREAD

**Issue by Etherum7** [ipfs-shipyard/ipld-explorer-components#282]
- OS Windows
 - Version of IPFS Desktop 0.12.2

When inspecting a file for peers after 2, 3 clicks it will show type error can not iterate over undefined.

Steps to reproduce the behavior are shown in the video attached 
[https://ipfs.io/ipfs/QmP91rLTnpW3R2kerLDhCX5b9nKWxWd5oj4fohBoaahunL?filename=ipfsError.mp4](url)

I expected to see some more peers but it resulted in an error, if no peers existed it should handle proper errors not just log its message.

final error
![image](https://user-images.githubusercontent.com/58840954/94997809-34f67880-05cb-11eb-8163-1fbf1084e7d6.png)

**Comment by jessicaschilling** [comment]
(NB: transferring to https://github.com/ipfs-shipyard/ipld-explorer-components since that's the upstream source of the problem)

**Comment by Etherum7** [comment]
Here it is QmP91rLTnpW3R2kerLDhCX5b9nKWxWd5oj4fohBoaahunL

**Comment by jessicaschilling** [comment]
Hi @Etherum7 -- quick diagnosis question for you if you don't mind. We've recently shipped some substantial improvements to the web UI (since your original report) and hope you can try to take the same steps in the new web UI to see if you receive no or a different error. If you can, please:
- Start Desktop as you normally would
- Open webui.ipfs.io in your browser (that address always uses the most recent version of the web UI)
- Try inspecting that same resource and see what happens (please include any screenshots that might be helpful, if you still experience problems)

Thank you so much 😊
